name: sydtest-webdriver-yesod
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - http-client
  - http-types
  - mtl
  - network-uri
  - path
  - path-io
  - sydtest
  - sydtest-wai
  - sydtest-webdriver
  - sydtest-yesod
  - text
  - webdriver
  - yesod



tests:
  sydtest-webdriver-yesod-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - path
    - path-io
    - sydtest
    - sydtest-webdriver
    - sydtest-webdriver-yesod
    - yesod
