- ignore:
    name: "Avoid lambda"
- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use const"
- ignore:
    name: "Use ||"
- ignore:
    name: "Avoid reverse"
- ignore:
    name: "Use ++"
- ignore:
    name: "Use void"
- ignore:
    name: "Reduce duplication"
- ignore:
    name: "Eta reduce"
- ignore:
    name: "Use first"
- ignore:
    name: "Avoid lambda using `infix`"
- ignore:
    name: "Redundant if"
- ignore:
    name: "Redundant lambda"
- ignore:
    name: "Redundant pure"
- ignore:
    name: "Use when"
