resolver: lts-22.22
packages:
- sydtest
- sydtest-aeson
- sydtest-autodocodec
- sydtest-discover
- sydtest-hedgehog
- sydtest-hedis
- sydtest-hspec
- sydtest-mongo
- sydtest-persistent
- sydtest-persistent-postgresql
- sydtest-persistent-sqlite
- sydtest-process
- sydtest-servant
- sydtest-typed-process
- sydtest-wai
- sydtest-webdriver
- sydtest-webdriver-screenshot
- sydtest-webdriver-yesod
- sydtest-yesod

- sydtest-test
- sydtest-misbehaved-test-suite

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wunused-packages -O0

extra-deps:
- github: NorfairKing/fast-myers-diff
  commit: d7c1a675af3889698b987485a630f96a993226fa
  subdirs:
    - fast-myers-diff
- github: NorfairKing/opt-env-conf
  commit: 1a8d79f4748ae566c525de8951ee6907ac3739a8
  subdirs:
    - opt-env-conf
    - opt-env-conf-test
- github: NorfairKing/autodocodec
  commit: d5f9869861d8678c7e6dfce339446fee490b8991
  subdirs:
    - autodocodec
    - autodocodec-nix
    - autodocodec-schema
    - autodocodec-yaml
- github: NorfairKing/validity
  commit: 9e58a7a6ed8cd59cb60ab426cef2edf6a1340b33
  subdirs:
    - validity
    - validity-aeson
    - validity-containers
    - validity-text
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text

- github: NorfairKing/safe-coloured-text
  commit: 61f14d21b7399fe97da24e484c2f9fedaf532bb8
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- tmp-postgres-1.34.1.0@sha256:a08a5fc554cfe19def3cb25bdbdb48456ab217669633ac01973231e1402d27cb,4959
- ansi-wl-pprint-0.6.9@sha256:fb737bc96e2aef34ad595d54ced7a73f648c521ebcb00fe0679aff45ccd49212,2448


system-ghc: true
nix:
  enable: false
with-hpack: hpack
