resolver: lts-22.22
packages:
- sydtest
- sydtest-aeson
- sydtest-autodocodec
- sydtest-discover
- sydtest-hedgehog
- sydtest-hedis
- sydtest-hspec
- sydtest-mongo
- sydtest-persistent
- sydtest-persistent-postgresql
- sydtest-persistent-sqlite
- sydtest-process
- sydtest-servant
- sydtest-typed-process
- sydtest-wai
- sydtest-webdriver
- sydtest-webdriver-screenshot
- sydtest-webdriver-yesod
- sydtest-yesod

- sydtest-test
- sydtest-misbehaved-test-suite

- /home/syd/src/autodocodec/autodocodec
- /home/syd/src/autodocodec/autodocodec-yaml
- /home/syd/src/autodocodec/autodocodec-schema
- /home/syd/src/opt-env-conf/opt-env-conf
- /home/syd/src/opt-env-conf/opt-env-conf-test
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wunused-packages -O0

extra-deps:
- fast-myers-diff-0.0.0

- github: NorfairKing/validity
  commit: 57c4897ccfeb3de60489e0328113798f059ef140
  subdirs:
    - validity
    - validity-aeson
    - validity-containers
    - validity-text
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text

- github: NorfairKing/safe-coloured-text
  commit: 61f14d21b7399fe97da24e484c2f9fedaf532bb8
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
    # - github: NorfairKing/autodocodec
    #   commit: a818df53b0f65caf3615d5cb9d4734288ff1ca39
    #   subdirs:
    #     - autodocodec
    #     - autodocodec-yaml
    #     - autodocodec-schema
      # - github: NorfairKing/opt-env-conf
      #   commit: 0f3d914b16551e88c1cc60060121c3da747c0a38
      #   subdirs:
      #     - opt-env-conf
      #     - opt-env-conf-test

system-ghc: true
nix:
  enable: false
with-hpack: hpack
