resolver: lts-24.16
packages:
- sydtest
- sydtest-aeson
- sydtest-autodocodec
- sydtest-discover
- sydtest-hedgehog
- sydtest-hedis
- sydtest-hspec
- sydtest-persistent
- sydtest-persistent-postgresql
- sydtest-persistent-sqlite
- sydtest-process
- sydtest-servant
- sydtest-typed-process
- sydtest-wai
- sydtest-webdriver
- sydtest-webdriver-screenshot
- sydtest-webdriver-yesod
- sydtest-yesod

- sydtest-test
- sydtest-misbehaved-test-suite

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wunused-packages -O0

extra-deps:
- github: NorfairKing/fast-myers-diff
  commit: 4a5c31884b8fc399085bffacd15d6cb5624b3177
  subdirs:
    - fast-myers-diff
- github: NorfairKing/opt-env-conf
  commit: b6da7e94827e89cc8af8c02e0f61d7a856a610d7
  subdirs:
    - opt-env-conf
    - opt-env-conf-test
- github: NorfairKing/autodocodec
  commit: 7439601de128dadf562430f4216cbdb28580ed20
  subdirs:
    - autodocodec
    - autodocodec-nix
    - autodocodec-schema
    - autodocodec-yaml
- github: NorfairKing/validity
  commit: 512aea6e0a112f5df09cc0b08f7fceffb122abc6
  subdirs:
    - validity
    - validity-aeson
    - validity-containers
    - validity-text
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text

- github: NorfairKing/safe-coloured-text
  commit: 9ed65a40b3b2fade447c9d5fcb941d58f6367308
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- tmp-postgres-1.34.1.0@sha256:a08a5fc554cfe19def3cb25bdbdb48456ab217669633ac01973231e1402d27cb,4959
- ansi-wl-pprint-0.6.9@sha256:fb737bc96e2aef34ad595d54ced7a73f648c521ebcb00fe0679aff45ccd49212,2448
- ansi-terminal-1.0.2@sha256:1f90bb88e670ce63fbf2c9216d50857f2419582f1c6791e542c3eab97ecfd364,2897
- ansi-terminal-types-0.11.5@sha256:f78440dfd95c4509e88855ac7cc2d9566ddf956a92c1290404cac93ad1a1b00a,1482


system-ghc: true
nix:
  enable: false
with-hpack: hpack
