name: sydtest-hspec
version: 0.4.0.4
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2021 Tom Sydney Kerckhove"
category: Testing
synopsis: An Hspec companion library for sydtest

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - hspec-core >=2.7.10
    - mtl
    - stm
    - sydtest >=0.18.0.0

tests:
  sydtest-hspec-test:
    main: Main.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - safe-coloured-text
    - stm
    - sydtest
    - sydtest-hspec
    - text
