name: sydtest-mutation
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
category: Testing

extra-source-files:
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - sydtest
  - sydtest-mutation-runtime

tests:
  sydtest-mutation-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson-pretty
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - path
    - sydtest
    - sydtest-mutation
    - sydtest-mutation-runtime
