name: sydtest-mutation-plugin
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
category: Testing

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Test.Syd.Mutation.Plugin
  - Test.Syd.Mutation.Plugin.Instrument
  - Test.Syd.Mutation.Plugin.Operator.IntLit1To0
  - Test.Syd.Mutation.Plugin.Operator.IntLitNTo0
  - Test.Syd.Mutation.Plugin.Operator.IntLitNTo1
  - Test.Syd.Mutation.Plugin.Operator.IntLitNegate
  - Test.Syd.Mutation.Plugin.Operator.Util
  - Test.Syd.Mutation.Plugin.Operators
  - Test.Syd.Mutation.Plugin.Operators.TH
  - Test.Syd.Mutation.Plugin.Runtime
  dependencies:
  - directory
  - filepath
  - ghc
  - mtl
  - path
  - path-io
  - sydtest-mutation-runtime
  - template-haskell
