name: sydtest-mutation-plugin
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
category: Testing

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - directory
  - filepath
  - ghc
  - mtl
  - path
  - path-io
  - sydtest-mutation-runtime
  - template-haskell
