{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeOperators #-}

-- | One extra check on top of "Test.Syd.Sqitch.Postgresql": after every sqitch
-- migration has been deployed, the resulting schema must equal the
-- schema that @persistent@'s automatic migration would produce against
-- an empty database.
--
-- This catches drift between hand-written sqitch migrations and the
-- ORM model, in both directions.
module Test.Syd.Sqitch.Postgresql.Persistent
  ( sqitchPersistentPostgresqlSpec,
    sqitchPersistentPostgresqlSpec',
    runSqitchPersistentChecks,
    SqitchPersistentSettings (..),
  )
where

import Control.Monad.Logger (runNoLoggingT)
import Data.Text (Text)
import qualified Database.Persist.Sql as DB
import Test.Syd
import Test.Syd.Persistent (migrationRunner)
import Test.Syd.Persistent.Postgresql (TemplateDB, persistPostgresqlSpec)
import Test.Syd.Sqitch.Postgresql

-- | Configuration for 'sqitchPersistentPostgresqlSpec'.
data SqitchPersistentSettings = SqitchPersistentSettings
  { -- | Settings forwarded to 'sqitchPostgresqlSpec' for the
    -- round-trip and idempotence checks.
    sqitchPersistentSqitch :: SqitchSettings,
    -- | The @persistent@ migration generated by @mkMigrate@.
    sqitchPersistentAutoMigration :: DB.Migration,
    -- | Anything else the application applies after automatic
    -- migration (indices, extensions). Run inside the same connection
    -- pool both for the persistent baseline /and/ after the sqitch
    -- deploy, so both snapshots include its effect. Use @pure ()@ if
    -- there is nothing extra to do.
    sqitchPersistentExtraSetup :: forall m. (MonadIO m) => DB.SqlPersistT m ()
  }

-- | Top-level entry point. Layers two suites on top of
-- 'persistPostgresqlSpec':
--
--   * The round-trip and idempotence checks from
--     'Test.Syd.Sqitch.sqitchPostgresqlSpec''.
--   * One additional test that compares the schema after deploying
--     every sqitch migration with the schema after running the
--     persistent automatic migration.
sqitchPersistentPostgresqlSpec ::
  SqitchPersistentSettings ->
  TestDef (TemplateDB ': outers) DB.ConnectionPool ->
  TestDef outers a
sqitchPersistentPostgresqlSpec settings inner =
  persistPostgresqlSpec (pure ()) $
    sqitchPersistentPostgresqlSpec' settings inner

-- | Variant that assumes 'TemplateDB' is already in the outer setup.
sqitchPersistentPostgresqlSpec' ::
  (HContains outers TemplateDB) =>
  SqitchPersistentSettings ->
  TestDef outers DB.ConnectionPool ->
  TestDef outers DB.ConnectionPool
sqitchPersistentPostgresqlSpec' settings rest =
  sqitchPostgresqlSpec' (sqitchPersistentSqitch settings) $
    describe "sqitch+persistent" $ do
      schemaEqualitySpec settings
      rest

schemaEqualitySpec ::
  forall outers.
  (HContains outers TemplateDB) =>
  SqitchPersistentSettings ->
  TestDef outers DB.ConnectionPool
schemaEqualitySpec settings =
  itWithAll "the sqitch deploy and the persistent automatic migration produce the same schema" $
    \(outers :: HList outers) (pool :: DB.ConnectionPool) ->
      runSqitchPersistentChecks settings (getElem outers) pool

-- | Run the schema-equality check in 'IO'. Exposed so callers (and
-- this package's own tests) can drive the check without going through
-- the 'TestDef' combinator.
runSqitchPersistentChecks ::
  SqitchPersistentSettings ->
  TemplateDB ->
  DB.ConnectionPool ->
  IO ()
runSqitchPersistentChecks settings tdb pool = do
  -- Phase 1: snapshot what persistent's automatic migration (plus the
  -- caller's extra setup) produces. Start from an empty schema so
  -- state left behind by an earlier test cannot pollute the snapshot.
  schemaFromPersistent <- runNoLoggingT $
    flip DB.runSqlPool pool $ do
      DB.rawExecute "DROP SCHEMA IF EXISTS public CASCADE" []
      DB.rawExecute "CREATE SCHEMA public" []
      DB.rawExecute "DROP SCHEMA IF EXISTS sqitch CASCADE" []
      migrationRunner (sqitchPersistentAutoMigration settings)
      sqitchPersistentExtraSetup settings
      querySchema

  -- Phase 2: clean the database and run sqitch deploy for the whole
  -- plan, then snapshot the sqitch side (also after the caller's
  -- extra setup, so anything setUpIndices and friends create is part
  -- of the comparison on both sides).
  testdb <- runNoLoggingT $
    flip DB.runSqlPool pool $ do
      [DB.Single dbName] <- DB.rawSql "SELECT current_database()::text" []
      pure (dbName :: Text)
  let sqitchSettings = sqitchPersistentSqitch settings
      target = sqitchTargetFromTemplateDB tdb testdb
  runNoLoggingT $
    flip DB.runSqlPool pool $ do
      DB.rawExecute "DROP SCHEMA IF EXISTS public CASCADE" []
      DB.rawExecute "CREATE SCHEMA public" []
      DB.rawExecute "DROP SCHEMA IF EXISTS sqitch CASCADE" []

  sqitchAt sqitchSettings target "deploy" ["--verify"]

  schemaFromSqitch <- runNoLoggingT $
    flip DB.runSqlPool pool $ do
      sqitchPersistentExtraSetup settings
      querySchema

  -- Phase 3: compare.
  compareSchemaSnapshots "sqitch migrations" schemaFromSqitch schemaFromPersistent

  -- Phase 4: revert so the database is clean for any downstream tests
  -- that share the same pool.
  sqitchRevertAll sqitchSettings target
