name: sydtest-aeson
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2021 Tom Sydney Kerckhove"
category: Testing
synopsis: An aeson companion library for sydtest

extra-source-files:
- LICENSE.md
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-pretty
  - bytestring
  - path
  - path-io
  - sydtest
  - text

tests:
  sydtest-aeson-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - aeson
    - sydtest
    - sydtest-aeson
    - text
