name: sydtest-yesod
version: 0.3.0.3
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020-2023 Tom Sydney Kerckhove"
category: Testing
synopsis: A yesod companion library for sydtest

extra-source-files:
- LICENSE.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - bytestring
    - case-insensitive
    - containers
    - binary
    - cookie
    - exceptions
    - http-client
    - http-client-tls
    - http-types
    - mtl
    - network
    - network-uri
    - sydtest >=0.3.0.0
    - sydtest-wai
    - text
    - time
    - wai
    - xml-conduit
    - yesod-core
    - yesod-test

tests:
  sydtest-yesod-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - conduit
    - cookie
    - http-client
    - path
    - path-io
    - sydtest
    - sydtest-wai
    - sydtest-yesod
    - text
    - yesod
    - yesod-core

  sydtest-yesod-blog-example-test:
    main: Spec.hs
    source-dirs: blog-example
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - http-client
    - monad-logger
    - mtl
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - sydtest
    - sydtest-persistent-sqlite
    - sydtest-wai
    - sydtest-yesod
    - text
    - yesod
