name: sydtest-webdriver-screenshot
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - JuicyPixels
  - bytestring
  - http-types
  - mtl
  - network-uri
  - path
  - path-io
  - sydtest
  - sydtest-wai
  - sydtest-webdriver
  - webdriver

tests:
  sydtest-webdriver-screenshot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-types
    - network-uri
    - sydtest
    - sydtest-wai
    - sydtest-webdriver
    - sydtest-webdriver-screenshot
    - wai 
