name: sydtest-mutation-runtime
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
category: Testing

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - aeson
  - autodocodec
  - bytestring
  - containers
  - fast-myers-diff
  - genvalidity
  - genvalidity-containers
  - genvalidity-path
  - genvalidity-text
  - path
  - path-io
  - text
