name: sydtest-mutation-example
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
category: Testing

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Example.Lib
  - Example.LibSpec
  - Example.UntestedLib
  - Example.ExceptionLib
  - Example.FunctionExceptionLib
  dependencies:
  - sydtest
  ghc-options:
  - -fno-full-laziness

tests:
  sydtest-mutation-example-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sydtest-mutation-example
    - sydtest
