name: sydtest-mutation-example
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
category: Testing

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -fno-full-laziness
  dependencies:
  - mtl >= 2 && < 3

