name: sydtest-discover
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020-2021 Tom Sydney Kerckhove"
category: Testing
synopsis: Automatic test suite discovery for sydtest

extra-source-files:
- LICENSE.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - filepath
  - optparse-applicative
  - path
  - path-io

executables:
  sydtest-discover:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sydtest-discover
