name: sydtest
version: 0.15.1.1
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020-2023 Tom Sydney Kerckhove"
category: Testing
synopsis: A modern testing framework for Haskell with good defaults and advanced testing features.
description: A modern testing framework for Haskell with good defaults and advanced testing features. Sydtest aims to make the common easy and the hard possible. See https://github.com/NorfairKing/sydtest#readme for more information.

extra-source-files:
- LICENSE.md
- CHANGELOG.md
- CONTRIBUTORS
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - MonadRandom
    - QuickCheck
    - async
    - autodocodec
    - autodocodec-yaml >=0.2.0.0
    - bytestring
    - containers
    - dlist
    - envparse
    - fast-myers-diff
    - filepath
    - mtl
    - optparse-applicative
    - path
    - path-io
    - pretty-show
    - quickcheck-io
    - random
    - random-shuffle
    - safe
    - safe-coloured-text
    - stm
    - svg-builder
    - text
    - vector
  when:
    - condition: 'os(windows)'
      then:
        dependencies:
          - ansi-terminal
      else:
        dependencies:
          - safe-coloured-text-terminfo
