name: sydtest
version: 0.9.0.0
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020-2022 Tom Sydney Kerckhove"
category: Testing
synopsis: A modern testing framework for Haskell with good defaults and advanced testing features.
description: A modern testing framework for Haskell with good defaults and advanced testing features. Sydtest aims to make the common easy and the hard possible. See https://github.com/NorfairKing/sydtest#readme for more information.

extra-source-files:
- LICENSE.md
- CHANGELOG.md
- CONTRIBUTORS
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - Diff
    - MonadRandom
    - QuickCheck
    - async
    - autodocodec
    - autodocodec-yaml
    - bytestring
    - containers
    - dlist
    - envparse
    - filepath
    - mtl
    - optparse-applicative
    - path
    - path-io
    - pretty-show
    - quickcheck-io
    - random-shuffle
    - safe
    - safe-coloured-text
    - split
    - stm
    - text
  when:
    - condition: 'os(windows)'
      then:
        dependencies:
          - ansi-terminal
      else:
        dependencies:
          - safe-coloured-text-terminfo

tests:
  sydtest-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - path
    - path-io
    - safe-coloured-text
    - stm
    - sydtest

  sydtest-output-test:
    main: Spec.hs
    source-dirs: output-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - path
    - path-io
    - random
    - safe-coloured-text
    - sydtest
    - text
    when:
      - condition: '!os(windows)'
        dependencies:
          - safe-coloured-text-terminfo
